<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>index.jsp</title>
</head>
<body>
<h1>데이터베이스 연동 예제....</h1>
	<%
		out.println("회원정보");
	%>
	<br/>
	<table>
	<tr>
	<td>ID</td>
	<td>PASSWD</td>
	<td>NAME</td>
	<td>NUM1</td>
	<td>NUM2</td>
	<td>EMAIL</td>
	<td>PHONE</td>
	<td>ZIPCODE/ADDRESS</td>
	<td>JOB</td>
	</tr>
	<tr>
	<td>${param.id1}</td>
	<td>${param.passwd1}</td>
	<td>${param.name1}</td>
	<td>${param.num11}</td>
	<td>${param.num21}</td>
	<td>${param.email1}</td>
	<td>${param.phone1}</td>
	<td>${param.zipcode1}/${param.address1}</td>
	<td>${param.job1}</td>
	</tr>
	<tr>
	<td>${param.id2}</td>
	<td>${param.passwd2}</td>
	<td>${param.name2}</td>
	<td>${param.num12}</td>
	<td>${param.num22}</td>
	<td>${param.email2}</td>
	<td>${param.phone2}</td>
	<td>${param.zipcode2}/${param.address2}</td>
	<td>${param.job1}</td>
	</tr>
	</table>
</body>
</html>